export default [
  {
      id: "1",
      name: "Yum",
      title: "Project: YumBox App Mobile",
      description: "UX/UI Design - Brand Design - Graphic Design",
      height: 257,
  },
  {
      id: "2",
      name: "STB",
      title: "Project: Lookbook Redesign",
      description: "UI Design",
      height: 257,
  },
  {
      id: "3",
      name: "SDO",
      title: "Project: Season Redesign",
      description: "UX/UI Design - Brand Design - Graphic Design",
      height: 257,
  },
  {
      id: "4",
      name: "Colores",
      title: "Project: Editorial Libro de los Colores",
      description: "Editorial Design - Graphic Design",
      height: 257,
  },
  {
      id: "5",
      name: "HCB",
      title: "Project: Newsletter Sketch",
      description: "UI Design",
      height: 257,
  },
  {
      id: "6",
      name: "Calza",
      title: "Project: Web Design",
      description: "UX/UI Design - Creation",
      height: 257,
  },
  {
      id: "7",
      name: "Malteadas",
      title: "Project: Brand Identity",
      description: "url Creation - UX/UI Design - Art Director",
      height: 257,
  },
  {
      id: "8",
      name: "Bonf",
      title: "Project: Corporate Manual",
      description: "Editorial Design - Graphic Design",
      height: 257,
  },
  {
      id: "9",
      name: "CHH",
      title: "Project: Logo Design",
      description: "Personal brand - Graphic Design",
      height: 257,
  },
  {
      id: "10",
      name: "Yumlato",
      title: "Project: Brand Identity",
      description: "Graphic proposal - Graphic Design",
      height: 257,
  }    
]